### ISSUE TITLE
 gapi is not defined

### ISSUE THREAD

**Issue by gustawdaniel** [itsCb/googleSignIn-vueJs#3]
On simple refresh "ctrl+r" everythin works, but when I clear cache by "ctrl+shift+r" I have error:

```
gapi is not defined
```

My settings:

```
    script: [
      {
        src: 'https://apis.google.com/js/platform.js',
        async: true,
        defer: true
      },
    ],
```

**Comment by itsCb** [comment]
It happens because you have async and defer attributes on your script tag. gapi would be loaded after your script tag. So remove the async and defer.
